import type { Deck } from "@/types/deck";
import type { Card } from "@/types/card";

// Scryfall snapshots captured 2026-09-08. Prices are deliberately omitted.
// This casual starter demonstrates the editor; it is not a tournament deck.
const cards: Card[] = [
  {
    "id": "7673784e-db4b-43a1-8d55-1bb9fc1e284f",
    "oracleId": "4457ed35-7c10-48c8-9776-456485fdf070",
    "name": "Lightning Bolt",
    "setCode": "msc",
    "setName": "Marvel Super Heroes Commander",
    "collectorNumber": "806",
    "releasedAt": "2026-06-26",
    "manaCost": "{R}",
    "manaValue": 1,
    "typeLine": "Instant",
    "oracleText": "Lightning Bolt deals 3 damage to any target.",
    "power": null,
    "toughness": null,
    "keywords": [],
    "colorIdentity": [
      "R"
    ],
    "legalities": {
      "standard": "not_legal",
      "future": "not_legal",
      "historic": "banned",
      "timeless": "legal",
      "gladiator": "legal",
      "pioneer": "not_legal",
      "modern": "legal",
      "legacy": "legal",
      "pauper": "legal",
      "vintage": "legal",
      "penny": "not_legal",
      "commander": "legal",
      "oathbreaker": "legal",
      "standardbrawl": "not_legal",
      "brawl": "legal",
      "competitivebrawl": "legal",
      "alchemy": "not_legal",
      "paupercommander": "legal",
      "duel": "legal",
      "oldschool": "not_legal",
      "premodern": "legal",
      "predh": "legal",
      "tlr": "legal"
    },
    "imageUrl": "https://cards.scryfall.io/normal/front/7/6/7673784e-db4b-43a1-8d55-1bb9fc1e284f.jpg?1783903008",
    "priceUsd": null,
    "artist": "Milivoj Ćeran",
    "scryfallUrl": "https://scryfall.com/card/msc/806/lightning-bolt?utm_source=api"
  },
  {
    "id": "bbc99a51-1501-4525-a3cc-f48249b64bed",
    "oracleId": "713332c1-5bd8-400f-bfff-c1ca0697a043",
    "name": "Opt",
    "setCode": "tdc",
    "setName": "Tarkir: Dragonstorm Commander",
    "collectorNumber": "158",
    "releasedAt": "2025-04-11",
    "manaCost": "{U}",
    "manaValue": 1,
    "typeLine": "Instant",
    "oracleText": "Scry 1. (Look at the top card of your library. You may put that card on the bottom.)\nDraw a card.",
    "power": null,
    "toughness": null,
    "keywords": [
      "Scry"
    ],
    "colorIdentity": [
      "U"
    ],
    "legalities": {
      "standard": "legal",
      "future": "legal",
      "historic": "legal",
      "timeless": "legal",
      "gladiator": "legal",
      "pioneer": "legal",
      "modern": "legal",
      "legacy": "legal",
      "pauper": "legal",
      "vintage": "legal",
      "penny": "not_legal",
      "commander": "legal",
      "oathbreaker": "legal",
      "standardbrawl": "legal",
      "brawl": "legal",
      "competitivebrawl": "legal",
      "alchemy": "legal",
      "paupercommander": "legal",
      "duel": "legal",
      "oldschool": "not_legal",
      "premodern": "legal",
      "predh": "legal",
      "tlr": "legal"
    },
    "imageUrl": "https://cards.scryfall.io/normal/front/b/b/bbc99a51-1501-4525-a3cc-f48249b64bed.jpg?1783907102",
    "priceUsd": null,
    "artist": "Craig J Spearing",
    "scryfallUrl": "https://scryfall.com/card/tdc/158/opt?utm_source=api"
  },
  {
    "id": "c0d74ecd-a595-4012-81b4-083264b40c94",
    "oracleId": "5fac139a-07d3-4e6c-98e3-d98b199f7a6f",
    "name": "Young Pyromancer",
    "setCode": "tdc",
    "setName": "Tarkir: Dragonstorm Commander",
    "collectorNumber": "95",
    "releasedAt": "2025-04-11",
    "manaCost": "{1}{R}",
    "manaValue": 2,
    "typeLine": "Creature — Human Shaman",
    "oracleText": "Whenever you cast an instant or sorcery spell, create a 1/1 red Elemental creature token.",
    "power": "2",
    "toughness": "1",
    "keywords": [],
    "colorIdentity": [
      "R"
    ],
    "legalities": {
      "standard": "not_legal",
      "future": "not_legal",
      "historic": "legal",
      "timeless": "legal",
      "gladiator": "legal",
      "pioneer": "legal",
      "modern": "legal",
      "legacy": "legal",
      "pauper": "not_legal",
      "vintage": "legal",
      "penny": "not_legal",
      "commander": "legal",
      "oathbreaker": "legal",
      "standardbrawl": "not_legal",
      "brawl": "legal",
      "competitivebrawl": "legal",
      "alchemy": "not_legal",
      "paupercommander": "not_legal",
      "duel": "legal",
      "oldschool": "not_legal",
      "premodern": "not_legal",
      "predh": "not_legal",
      "tlr": "legal"
    },
    "imageUrl": "https://cards.scryfall.io/normal/front/c/0/c0d74ecd-a595-4012-81b4-083264b40c94.jpg?1783907139",
    "priceUsd": null,
    "artist": "Alessandra Pisano",
    "scryfallUrl": "https://scryfall.com/card/tdc/95/young-pyromancer?utm_source=api"
  },
  {
    "id": "d6bfa227-4309-40ed-952c-279595eab17e",
    "oracleId": "dafd2713-d1bc-474b-b390-d2ff20b5375e",
    "name": "Monastery Swiftspear",
    "setCode": "bro",
    "setName": "The Brothers' War",
    "collectorNumber": "144",
    "releasedAt": "2022-11-18",
    "manaCost": "{R}",
    "manaValue": 1,
    "typeLine": "Creature — Human Monk",
    "oracleText": "Haste\nProwess (Whenever you cast a noncreature spell, this creature gets +1/+1 until end of turn.)",
    "power": "1",
    "toughness": "2",
    "keywords": [
      "Prowess",
      "Haste"
    ],
    "colorIdentity": [
      "R"
    ],
    "legalities": {
      "standard": "not_legal",
      "future": "not_legal",
      "historic": "legal",
      "timeless": "legal",
      "gladiator": "legal",
      "pioneer": "legal",
      "modern": "legal",
      "legacy": "legal",
      "pauper": "banned",
      "vintage": "legal",
      "penny": "not_legal",
      "commander": "legal",
      "oathbreaker": "legal",
      "standardbrawl": "not_legal",
      "brawl": "legal",
      "competitivebrawl": "legal",
      "alchemy": "not_legal",
      "paupercommander": "legal",
      "duel": "legal",
      "oldschool": "not_legal",
      "premodern": "not_legal",
      "predh": "not_legal",
      "tlr": "legal"
    },
    "imageUrl": "https://cards.scryfall.io/normal/front/d/6/d6bfa227-4309-40ed-952c-279595eab17e.jpg?1783920066",
    "priceUsd": null,
    "artist": "Gabor Szikszai",
    "scryfallUrl": "https://scryfall.com/card/bro/144/monastery-swiftspear?utm_source=api"
  },
  {
    "id": "fc9a66a1-367c-4035-a22e-00fab55be5a0",
    "oracleId": "b2c6aa39-2d2a-459c-a555-fb48ba993373",
    "name": "Island",
    "setCode": "m21",
    "setName": "Core Set 2021",
    "collectorNumber": "263",
    "releasedAt": "2020-07-03",
    "manaCost": "",
    "manaValue": 0,
    "typeLine": "Basic Land — Island",
    "oracleText": "({T}: Add {U}.)",
    "power": null,
    "toughness": null,
    "keywords": [],
    "colorIdentity": [
      "U"
    ],
    "legalities": {
      "standard": "legal",
      "future": "legal",
      "historic": "legal",
      "timeless": "legal",
      "gladiator": "legal",
      "pioneer": "legal",
      "modern": "legal",
      "legacy": "legal",
      "pauper": "legal",
      "vintage": "legal",
      "penny": "legal",
      "commander": "legal",
      "oathbreaker": "legal",
      "standardbrawl": "legal",
      "brawl": "legal",
      "competitivebrawl": "legal",
      "alchemy": "legal",
      "paupercommander": "legal",
      "duel": "legal",
      "oldschool": "not_legal",
      "premodern": "legal",
      "predh": "legal",
      "tlr": "legal"
    },
    "imageUrl": "https://cards.scryfall.io/normal/front/f/c/fc9a66a1-367c-4035-a22e-00fab55be5a0.jpg?1783930645",
    "priceUsd": null,
    "artist": "Cliff Childs",
    "scryfallUrl": "https://scryfall.com/card/m21/263/island?utm_source=api"
  },
  {
    "id": "b92c8925-ecfc-4ece-b83a-f12e98a938ab",
    "oracleId": "a3fb7228-e76b-4e96-a40e-20b5fed75685",
    "name": "Mountain",
    "setCode": "m21",
    "setName": "Core Set 2021",
    "collectorNumber": "269",
    "releasedAt": "2020-07-03",
    "manaCost": "",
    "manaValue": 0,
    "typeLine": "Basic Land — Mountain",
    "oracleText": "({T}: Add {R}.)",
    "power": null,
    "toughness": null,
    "keywords": [],
    "colorIdentity": [
      "R"
    ],
    "legalities": {
      "standard": "legal",
      "future": "legal",
      "historic": "legal",
      "timeless": "legal",
      "gladiator": "legal",
      "pioneer": "legal",
      "modern": "legal",
      "legacy": "legal",
      "pauper": "legal",
      "vintage": "legal",
      "penny": "legal",
      "commander": "legal",
      "oathbreaker": "legal",
      "standardbrawl": "legal",
      "brawl": "legal",
      "competitivebrawl": "legal",
      "alchemy": "legal",
      "paupercommander": "legal",
      "duel": "legal",
      "oldschool": "not_legal",
      "premodern": "legal",
      "predh": "legal",
      "tlr": "legal"
    },
    "imageUrl": "https://cards.scryfall.io/normal/front/b/9/b92c8925-ecfc-4ece-b83a-f12e98a938ab.jpg?1783930645",
    "priceUsd": null,
    "artist": "Cliff Childs",
    "scryfallUrl": "https://scryfall.com/card/m21/269/mountain?utm_source=api"
  }
];

export function createSampleDeck(): Deck {
  const quantities = [4, 4, 4, 4, 10, 10];
  return {
    id: "sample-izzet-spells",
    name: "Izzet Spells — sample",
    format: "casual",
    createdAt: "2026-09-08T00:00:00.000Z",
    updatedAt: "2026-09-08T00:00:00.000Z",
    cards: cards.map((card, index) => ({
      card,
      quantity: quantities[index],
      zone: "mainboard",
    })),
  };
}

